version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'helical-client-449903-f1') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'de2025zoomcamp') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_table
      - name: yellow_table
      - name: fhv_table

models:
  - name: stg_staging__yellow_table
  - name: stg_staging__green_table
  - name: stg_staging__fhv_table
